// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmkTgH1PNx8j80cNhfmXO66bT-zQRtDhU',
    appId: '1:1028512032004:web:2e40d1818cc189fcc4dc51',
    messagingSenderId: '1028512032004',
    projectId: 'motafawik-7844c',
    authDomain: 'motafawik-7844c.firebaseapp.com',
    storageBucket: 'motafawik-7844c.firebasestorage.app',
    measurementId: 'G-BWQSYVD2ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJXFtrjLbx186RG-ZV6hRFawsg9nMV4gI',
    appId: '1:1028512032004:android:4aa1f4d8215aaa8bc4dc51',
    messagingSenderId: '1028512032004',
    projectId: 'motafawik-7844c',
    storageBucket: 'motafawik-7844c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD33gpVmchj1F1RdlM9pC2EbnLJGsWfgfM',
    appId: '1:1028512032004:ios:7b65a9a43195dc31c4dc51',
    messagingSenderId: '1028512032004',
    projectId: 'motafawik-7844c',
    storageBucket: 'motafawik-7844c.firebasestorage.app',
    iosBundleId: 'com.example.alMotafawiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD33gpVmchj1F1RdlM9pC2EbnLJGsWfgfM',
    appId: '1:1028512032004:ios:7b65a9a43195dc31c4dc51',
    messagingSenderId: '1028512032004',
    projectId: 'motafawik-7844c',
    storageBucket: 'motafawik-7844c.firebasestorage.app',
    iosBundleId: 'com.example.alMotafawiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmkTgH1PNx8j80cNhfmXO66bT-zQRtDhU',
    appId: '1:1028512032004:web:033ff9227287bb98c4dc51',
    messagingSenderId: '1028512032004',
    projectId: 'motafawik-7844c',
    authDomain: 'motafawik-7844c.firebaseapp.com',
    storageBucket: 'motafawik-7844c.firebasestorage.app',
    measurementId: 'G-KPMCGCYND4',
  );
}
